### PR TITLE
Added Grokking Artificial Intelligence Algorithms

### PR DESCRIPTION
**Pull request by ipcenas**
Hello, 
Branko from Manning Publications here. 
I thought this title of ours could be a good fit for the list.
Thanks for checking it out!
Cheers

### CODE REVIEW

**Comment by zslucky** [comment]
Thanks for contributing @ipcenas , The book looks great, but I found this is a `COMMERCIAL` book, so it should marked as `COMMERCIAL` like books in category `Philosophy `. And I also rename the category `Introductory theory` to `Introductory theory and get start`, this books looks like suitable for this category, do you agree?

**Comment by ipcenas** [comment]
Hi, I am sorry, I must have overlooked it. Thanks, I do agree with that categorization.

**Comment by zslucky** [comment]
Thanks, I will merge it when you finish the work. 👍

**Comment by zslucky** [comment]
Manually add the book with my another change, so close this PR, thanks for your contributing. 😄

**Pull request closed without merging**
